# noqa
WEATHER_GIFS = {
    "Sunny": "sunny.svg",
    "Clear": "sunny.svg",
    "Partly cloudy": "partial_cloudy.svg",
    "Cloudy": "cloudy.svg",
    "Overcast": "cloudy.svg",
    "Mist": "cloudy.svg",
    "Patchy rain possible": "rainy.svg",
    "Patchy sleet possible": "snowy.svg",
    "Patchy freezing drizzle possible": "snowy.svg",
    "Thundery outbreaks possible": "stormy.svg",
    "Blowing snow": "snowy.svg",
    "Blizzard": "snowy.svg",
    "Fog": "cloudy.svg",
    "Freezing fog": "snowy.svg",
    "Patchy light drizzle": "rainy.svg",
    "Light drizzle": "rainy.svg",
    "Freezing drizzle": "snowy.svg",
    "Heavy freezing drizzle": "snowy.svg",
    "Patchy light rain": "rainy.svg",
    "Light rain": "rainy.svg",
    "Moderate rain at times": "rainy.svg",
    "Moderate rain": "rainy.svg",
    "Heavy rain at times": "rainy.svg",
    "Heavy rain": "rainy.svg",
    "Light freezing rain": "rainy.svg",
}

ERRORS = {
    104: "Limited Exceeded",
    601: "An invalid (or missing) query value was specified.",
    615: "City not Founded",
}

EXAMPLE_RESPONSE = {
    "request": {"type": "City", "query": "New York, United States of America", "language": "en", "unit": "m"},
    "location": {
        "name": "New York",
        "country": "United States of America",
        "region": "New York",
        "lat": "40.714",
        "lon": "-74.006",
        "timezone_id": "America/New_York",
        "localtime": "2019-09-07 08:14",
        "localtime_epoch": 1567844040,
        "utc_offset": "-4.0",
    },
    "current": {
        "observation_time": "12:14 PM",
        "temperature": 13,
        "weather_code": 113,
        "weather_icons": ["https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png"],
        "weather_descriptions": ["Thundery outbreaks possible"],
        "wind_speed": 0,
        "wind_degree": 349,
        "wind_dir": "N",
        "pressure": 1010,
        "precip": 0,
        "humidity": 90,
        "cloudcover": 0,
        "feelslike": 13,
        "uv_index": 4,
        "visibility": 16,
    },
}
